[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc = "0.8.20"

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.3.0-rc.0"

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true

remappings = [
    "@openzeppelin-contracts/=dependencies/@openzeppelin-contracts-5.3.0-rc.0/",
   "forge-std/=dependencies/forge-std-1.9.6/src/"
   
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
